name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  #test-deploy:
  #  if: github.event_name != 'push'
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: actions/setup-node@v3
  #      with:
  #        node-version: 18
  #        cache: yarn
  #    - name: Install dependencies
  #      run: yarn install --frozen-lockfile
  #    - name: Test build website
  #      run: yarn build
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup build env
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: build
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
